#!/usr/bin/env python3

import os
import os.path

import sys
import glob

def main(args):
    if len(args)<2:
        print('Not enough arguments given!')
        print('Usage is:')
        print('    genmpeg prefix output_file.mpg')
        exit(1)

    prefix, outfname = args
    
    for fn in glob.glob(prefix + '*.tif'):
        nfn = fn + '.jpg'
        if (not os.path.exists(nfn)):
            print('{} -> {}'.format(fn, nfn))
            os.system('convert -quality 100 {} {}'.format(fn, nfn))

    os.system('ffmpeg -r 30 -b 2400 -i {prefix}%03d.tif.jpg -q 4 {outfile}'.format(prefix=prefix, outfile=outfname))


if __name__=='__main__':
    main(sys.argv[1:])
