#!/usr/bin/env python3

import os
import sys
import glob

def main(args):
    if len(args)<2:
        print('Not enough arguments given!')
        print('Usage is:')
        print('    genmpeg prefix output_file.mpg')
        exit(1)

    prefix, outfname = args
    
    for fn in glob.glob(prefix + '*.tif'):
        nfn = fn + '.jpg'
        print('{} -> {}'.format(fn, nfn))
        os.system('convert -quality 100 {} {}'.format(fn, nfn))
        
    os.system('mencoder "mf://{}*.tif.jpg" -oac lavc -ovc lavc -lavcopts acodec=mp2:vcodec=mpeg2video:mbd=1:vbitrate=3800 -of mpeg -o {}'.format(prefix, outfname))


if __name__=='__main__':
    main(sys.argv[1:])
