RENDERMANDIR = ${DELIGHT}

main: main.cpp Makefile
	g++ -m32 -g -o main main.cpp -I${RENDERMANDIR}/include -L${RENDERMANDIR}/lib/ -l3delight -lm -ldl -lc

# main: main.cpp Makefile
# 	g++ -g -o main main.cpp -I /usr/local/include/aqsis -laqsis -lm -ldl -lc
